---

apiVersion: v1 
kind: Service 
metadata:
    name: service-backend 
spec:
    type: NodePort
    ports:
     - targetPort: 8080
       port: 8080
       nodePort: 30016
    selector:
       app: backend
       type: backend
    sessionAffinity: None
    type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresql
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root
  POSTGRES_DATABASE: postgresql

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql/

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
           - name: PETCLINIC_JDBC_URL
             value: jdbc:postgresql://postgresql/petclinic
           - name: PETCLINIC_JDBC_USER
             value: root
           - name: PETCLINIC_JDBC_PASSWORD
             value: org.hibernate.dialect.PostgreSQLDialect
           - name: PETCLINIC_JDBC_DIALECT
             value: org.hibernate.dialect.PostgreSQLDialect
           - name: POSTGRES_PASSWORD
             value: root
           - name: POSTGRES_DB
             value: postgres
           - name: POSTGRES_DATABASE
             value: postgres
           - name: POSTGRES_USER
             value: root

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres
